//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLMakeTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLMakeTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER CLUSTER personnel
        ///   SIZE 1024 CACHE;.
        /// </summary>
        internal static string AlterCluster {
            get {
                return ResourceManager.GetString("AlterCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER DATABASE 
        ///   DEFAULT TEMPORARY TABLESPACE test;.
        /// </summary>
        internal static string AlterDatabase {
            get {
                return ResourceManager.GetString("AlterDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER DATABASE LINK test_link CONNECT TO scott IDENTIFIED BY tiger;.
        /// </summary>
        internal static string AlterDatabaseLink {
            get {
                return ResourceManager.GetString("AlterDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER DIMENSION customers_dim
        ///   DROP ATTRIBUTE country;.
        /// </summary>
        internal static string AlterDimension {
            get {
                return ResourceManager.GetString("AlterDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER DISKGROUP dgroup_01
        ///  MOUNT;.
        /// </summary>
        internal static string AlterDiskgroup {
            get {
                return ResourceManager.GetString("AlterDiskgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER FLASHBACK ARCHIVE test SET DEFAULT;.
        /// </summary>
        internal static string AlterFlashbackArchive {
            get {
                return ResourceManager.GetString("AlterFlashbackArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER FUNCTION scott.test_function COMPILE;.
        /// </summary>
        internal static string AlterFunction {
            get {
                return ResourceManager.GetString("AlterFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER INDEX oe.test_ix  
        ///    INITRANS 5;.
        /// </summary>
        internal static string AlterIndex {
            get {
                return ResourceManager.GetString("AlterIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER INDEXTYPE test_indextype COMPILE;.
        /// </summary>
        internal static string AlterIndextype {
            get {
                return ResourceManager.GetString("AlterIndextype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER JAVA CLASS &quot;Agent&quot;
        ///   RESOLVER ((&quot;/usr/bin/bfile_dir/*&quot; pm)(* public))
        ///   RESOLVE;.
        /// </summary>
        internal static string AlterJavaClass {
            get {
                return ResourceManager.GetString("AlterJavaClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER java source SCOTT.&quot;Generated/TESTSTAPI&quot; compile;.
        /// </summary>
        internal static string AlterJavaSource {
            get {
                return ResourceManager.GetString("AlterJavaSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER LIBRARY scott.test_ext_lib COMPILE;.
        /// </summary>
        internal static string AlterLibrary {
            get {
                return ResourceManager.GetString("AlterLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER MATERIALIZED VIEW sales_by_month_by_state CONSIDER FRESH;.
        /// </summary>
        internal static string AlterMaterializedView {
            get {
                return ResourceManager.GetString("AlterMaterializedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER MATERIALIZED VIEW LOG ON order_items ADD ROWID;.
        /// </summary>
        internal static string AlterMaterializedViewLog {
            get {
                return ResourceManager.GetString("AlterMaterializedViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER OPERATOR test_op COMPILE;.
        /// </summary>
        internal static string AlterOperator {
            get {
                return ResourceManager.GetString("AlterOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER OUTLINE bluberies REBUILD;.
        /// </summary>
        internal static string AlterOutline {
            get {
                return ResourceManager.GetString("AlterOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PACKAGE test_package COMPILE PACKAGE;.
        /// </summary>
        internal static string AlterPackage {
            get {
                return ResourceManager.GetString("AlterPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER private OUTLINE bluberies REBUILD;.
        /// </summary>
        internal static string AlterPrivateOutline {
            get {
                return ResourceManager.GetString("AlterPrivateOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE scott.test_proc COMPILE;.
        /// </summary>
        internal static string AlterProcedure {
            get {
                return ResourceManager.GetString("AlterProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROFILE test_profile 
        ///   LIMIT PASSWORD_REUSE_TIME 30 
        ///   PASSWORD_REUSE_MAX UNLIMITED;.
        /// </summary>
        internal static string AlterProfile {
            get {
                return ResourceManager.GetString("AlterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PUBLIC DATABASE LINK test_link CONNECT TO scott IDENTIFIED BY tiger;.
        /// </summary>
        internal static string AlterPublicDatabaseLink {
            get {
                return ResourceManager.GetString("AlterPublicDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER public OUTLINE bluberies REBUILD;.
        /// </summary>
        internal static string AlterPublicOutline {
            get {
                return ResourceManager.GetString("AlterPublicOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER RESOURCE COST 
        ///   CPU_PER_SESSION 100
        ///   CONNECT_TIME      1;.
        /// </summary>
        internal static string AlterResourceCost {
            get {
                return ResourceManager.GetString("AlterResourceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER ROLE dw_manager IDENTIFIED USING scott.admin;.
        /// </summary>
        internal static string AlterRole {
            get {
                return ResourceManager.GetString("AlterRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER ROLLBACK SEGMENT rbs_one ONLINE;.
        /// </summary>
        internal static string AlterRollbackSegment {
            get {
                return ResourceManager.GetString("AlterRollbackSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER SEQUENCE test_seq 
        ///   CYCLE
        ///   CACHE 5;.
        /// </summary>
        internal static string AlterSequence {
            get {
                return ResourceManager.GetString("AlterSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER SESSION 
        ///   SET SQL_TRACE = TRUE;.
        /// </summary>
        internal static string AlterSession {
            get {
                return ResourceManager.GetString("AlterSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER shared DATABASE LINK test_link CONNECT TO scott IDENTIFIED BY tiger;.
        /// </summary>
        internal static string AlterSharedDatabaseLink {
            get {
                return ResourceManager.GetString("AlterSharedDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER shared public DATABASE LINK test_link CONNECT TO scott IDENTIFIED BY tiger;.
        /// </summary>
        internal static string AlterSharedPublicDatabaseLink {
            get {
                return ResourceManager.GetString("AlterSharedPublicDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER SYSTEM SWITCH LOGFILE;.
        /// </summary>
        internal static string AlterSystem {
            get {
                return ResourceManager.GetString("AlterSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE students ADD UNIQUE (student_id);.
        /// </summary>
        internal static string AlterTable {
            get {
                return ResourceManager.GetString("AlterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE suppliers
        ///add CONSTRAINT check_supplier_name
        ///   CHECK (supplier_name IN (&apos;IBM&apos;, &apos;Microsoft&apos;, &apos;NVIDIA&apos;));.
        /// </summary>
        internal static string AlterTableAddConstraintCheck {
            get {
                return ResourceManager.GetString("AlterTableAddConstraintCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE students
        ///  ADD CONSTRAINT school_fk FOREIGN KEY (school_id) 
        ///  REFERENCES scholls (scholl_id);.
        /// </summary>
        internal static string AlterTableAddConstraintForeign {
            get {
                return ResourceManager.GetString("AlterTableAddConstraintForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table students
        ///add constraint students_pk primary key (ID);.
        /// </summary>
        internal static string AlterTableAddConstraintPrimary {
            get {
                return ResourceManager.GetString("AlterTableAddConstraintPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alter table students
        ///  add constraint student_uk
        ///  unique (student_id).
        /// </summary>
        internal static string AlterTableAddConstraintUnique {
            get {
                return ResourceManager.GetString("AlterTableAddConstraintUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE departments
        ///    DROP CONSTRAINT pk_dept CASCADE;.
        /// </summary>
        internal static string AlterTableDropConstraint {
            get {
                return ResourceManager.GetString("AlterTableDropConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE departments 
        ///    DROP PRIMARY KEY CASCADE;.
        /// </summary>
        internal static string AlterTableDropPrimaryKey {
            get {
                return ResourceManager.GetString("AlterTableDropPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE employees 
        ///    DROP UNIQUE (email);.
        /// </summary>
        internal static string AlterTableDropUnique {
            get {
                return ResourceManager.GetString("AlterTableDropUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AlterTableModifyConstraint {
            get {
                return ResourceManager.GetString("AlterTableModifyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE customers RENAME CONSTRAINT cust_fname_nn
        ///   TO cust_firstname_nn;.
        /// </summary>
        internal static string AlterTableRenameConstraint {
            get {
                return ResourceManager.GetString("AlterTableRenameConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLESPACE demo ONLINE;.
        /// </summary>
        internal static string AlterTablespace {
            get {
                return ResourceManager.GetString("AlterTablespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TRIGGER journal_trg DISABLE;.
        /// </summary>
        internal static string AlterTrigger {
            get {
                return ResourceManager.GetString("AlterTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TYPE phone_list_typ
        ///  MODIFY ELEMENT TYPE VARCHAR(64) CASCADE;.
        /// </summary>
        internal static string AlterType {
            get {
                return ResourceManager.GetString("AlterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER USER app_user REVOKE CONNECT THROUGH core;.
        /// </summary>
        internal static string AlterUser {
            get {
                return ResourceManager.GetString("AlterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW demo_v
        ///    COMPILE;.
        /// </summary>
        internal static string AlterView {
            get {
                return ResourceManager.GetString("AlterView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYZE CLUSTER test_cluster
        ///    VALIDATE STRUCTURE CASCADE;.
        /// </summary>
        internal static string AnalyzeCluster {
            get {
                return ResourceManager.GetString("AnalyzeCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYZE INDEX test_i VALIDATE STRUCTURE;.
        /// </summary>
        internal static string AnalyzeIndex {
            get {
                return ResourceManager.GetString("AnalyzeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYZE TABLE hr.orders DELETE STATISTICS;.
        /// </summary>
        internal static string AnalyzeTable {
            get {
                return ResourceManager.GetString("AnalyzeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSOCIATE STATISTICS WITH PACKAGES special_functions, other_functions, last_functions DEFAULT SELECTIVITY 10;.
        /// </summary>
        internal static string AssociateStatistics {
            get {
                return ResourceManager.GetString("AssociateStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUDIT DELETE ANY TABLE;.
        /// </summary>
        internal static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL emp_mgmt.remove_dept@dblink(100) INTO :x;.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENT ON COLUMN hr.orders.name 
        ///   IS &apos;Test comment&apos;;.
        /// </summary>
        internal static string CommentColumn {
            get {
                return ResourceManager.GetString("CommentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment on edition test_edition is &apos;Test comment&apos;;.
        /// </summary>
        internal static string CommentEdition {
            get {
                return ResourceManager.GetString("CommentEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment on indextype test_indextype is &apos;Test comment&apos;;.
        /// </summary>
        internal static string CommentIndextype {
            get {
                return ResourceManager.GetString("CommentIndextype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment on materialized view test_mv is &apos;Test comment&apos;;.
        /// </summary>
        internal static string CommentMaterializedView {
            get {
                return ResourceManager.GetString("CommentMaterializedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment on mining model test_mining_model is &apos;Test comment&apos;;.
        /// </summary>
        internal static string CommentMiningModel {
            get {
                return ResourceManager.GetString("CommentMiningModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment on operator test_operator is &apos;Test comment&apos;;.
        /// </summary>
        internal static string CommentOperator {
            get {
                return ResourceManager.GetString("CommentOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment on table hr.orders is &apos;Test comment&apos;;.
        /// </summary>
        internal static string CommentTable {
            get {
                return ResourceManager.GetString("CommentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMIT FORCE &apos;22.57.53&apos;;.
        /// </summary>
        internal static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE BIGFILE TABLESPACE bigtbs_01
        ///  DATAFILE &apos;tbs_f1.dbf&apos;
        ///  SIZE 20M AUTOEXTEND ON;.
        /// </summary>
        internal static string CreateBigfileTablespace {
            get {
                return ResourceManager.GetString("CreateBigfileTablespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE BITMAP INDEX product_bm_ix
        ///   ON hash_products(list_price)
        ///   FROM hash_products h, sales_quota s
        ///   WHERE h.product_id = s.product_id
        ///   TABLESPACE example
        ///   LOCAL(PARTITION ix_p1 TABLESPACE example,
        ///         PARTITION ix_p2,
        ///         PARTITION ix_p3 TABLESPACE example,
        ///         PARTITION ix_p4,
        ///         PARTITION ix_p5 TABLESPACE example );.
        /// </summary>
        internal static string CreateBitmapIndex {
            get {
                return ResourceManager.GetString("CreateBitmapIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTER personnel
        ///   (department NUMBER(4))
        ///SIZE 512 
        ///STORAGE (initial 100K next 50K);.
        /// </summary>
        internal static string CreateCluster {
            get {
                return ResourceManager.GetString("CreateCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE CONTEXT hr_context USING emp_mgmt;.
        /// </summary>
        internal static string CreateContext {
            get {
                return ResourceManager.GetString("CreateContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CONTROLFILE SET DATABASE &quot;TEST&quot; RESETLOGS NOARCHIVELOG
        ///    MAXLOGFILES 32
        ///    MAXLOGMEMBERS 5
        ///    MAXDATAFILES 600
        ///    MAXINSTANCES 10
        ///    MAXLOGHISTORY 1000
        ///LOGFILE
        ///  GROUP 1 (
        ///    &apos;/u03/app/oradata/TEST/redo_g01a.log&apos;,
        ///    &apos;/u04/app/oradata/TEST/redo_g01b.log&apos;,
        ///    &apos;/u05/app/oradata/TEST/redo_g01c.log&apos;
        ///  ) SIZE 200K,
        ///  GROUP 2 (
        ///    &apos;/u03/app/oradata/TEST/redo_g02a.log&apos;,
        ///    &apos;/u04/app/oradata/TEST/redo_g02b.log&apos;,
        ///    &apos;/u05/app/oradata/TEST/redo_g02c.log&apos;
        ///  ) SIZE 200K,
        ///  GROUP 3 (        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateControlFile {
            get {
                return ResourceManager.GetString("CreateControlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE sample
        ///   CONTROLFILE REUSE 
        ///   LOGFILE
        ///      GROUP 1 (&apos;diskx:log1.log&apos;, &apos;disky:log1.log&apos;) SIZE 50K, 
        ///      GROUP 2 (&apos;diskx:log2.log&apos;, &apos;disky:log2.log&apos;) SIZE 50K 
        ///   MAXLOGFILES 5 
        ///   MAXLOGHISTORY 100 
        ///   MAXDATAFILES 10 
        ///   MAXINSTANCES 2 
        ///   ARCHIVELOG 
        ///   CHARACTER SET AL32UTF8
        ///   NATIONAL CHARACTER SET AL16UTF16
        ///   DATAFILE  
        ///      &apos;disk1:df1.dbf&apos; AUTOEXTEND ON,
        ///      &apos;disk2:df2.dbf&apos; AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
        ///   DEFAULT TEMPORARY TABLESPACE temp_ts
        ///   UNDO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE LINK local 
        ///   CONNECT TO hr IDENTIFIED BY password
        ///   USING &apos;local&apos;;.
        /// </summary>
        internal static string CreateDatabaseLink {
            get {
                return ResourceManager.GetString("CreateDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DIMENSION customers_dim 
        ///   LEVEL customer   IS (customers.cust_id)
        ///   LEVEL city       IS (customers.cust_city) 
        ///   LEVEL state      IS (customers.cust_state_province) 
        ///   LEVEL country    IS (countries.country_id) 
        ///   LEVEL subregion  IS (countries.country_subregion) 
        ///   LEVEL region     IS (countries.country_region) 
        ///   HIERARCHY geog_rollup (
        ///      customer      CHILD OF
        ///      city          CHILD OF 
        ///      state         CHILD OF 
        ///      country       CHILD OF 
        ///      subregion     CHILD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDimension {
            get {
                return ResourceManager.GetString("CreateDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE DIRECTORY bfile_dir AS &apos;/usr/bin/bfile_dir&apos;;.
        /// </summary>
        internal static string CreateDirectory {
            get {
                return ResourceManager.GetString("CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DISKGROUP dgroup_01
        ///  EXTERNAL REDUNDANCY
        ///  DISK &apos;$ORACLE_HOME/disks/c*&apos;;.
        /// </summary>
        internal static string CreateDiskgroup {
            get {
                return ResourceManager.GetString("CreateDiskgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE EDITION test_ed;.
        /// </summary>
        internal static string CreateEdition {
            get {
                return ResourceManager.GetString("CreateEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR replace EDITIONING VIEW ed_orders_view (o_id, o_date, o_status)
        ///  AS SELECT order_id, order_date, order_status FROM orders
        ///  WITH READ ONLY;.
        /// </summary>
        internal static string CreateEditioningView {
            get {
                return ResourceManager.GetString("CreateEditioningView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE FLASHBACK ARCHIVE DEFAULT test_archive1
        ///   TABLESPACE example
        ///   QUOTA 1 M
        ///   RETENTION 1 DAY;.
        /// </summary>
        internal static string CreateFlashbackArchive {
            get {
                return ResourceManager.GetString("CreateFlashbackArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE FORCE VIEW emp_view AS 
        ///   SELECT last_name, salary*12 annual_salary
        ///   FROM employees 
        ///   WHERE department_id = 20;.
        /// </summary>
        internal static string CreateForceView {
            get {
                return ResourceManager.GetString("CreateForceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE or replace FUNCTION get_bal(acc_no IN NUMBER) 
        ///   RETURN NUMBER 
        ///   IS acc_bal NUMBER(11,2);
        ///   BEGIN 
        ///      SELECT order_total 
        ///      INTO acc_bal 
        ///      FROM orders 
        ///      WHERE customer_id = acc_no; 
        ///      RETURN(acc_bal); 
        ///    END;
        ////.
        /// </summary>
        internal static string CreateFunction {
            get {
                return ResourceManager.GetString("CreateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE GLOBAL TEMPORARY TABLE today_sales
        ///   ON COMMIT PRESERVE ROWS 
        ///   AS SELECT * FROM orders WHERE order_date = SYSDATE;.
        /// </summary>
        internal static string CreateGlobalTemporaryTable {
            get {
                return ResourceManager.GetString("CreateGlobalTemporaryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX ord_customer_ix
        ///   ON orders (customer_id);.
        /// </summary>
        internal static string CreateIndex {
            get {
                return ResourceManager.GetString("CreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR replace INDEXTYPE position_indextype
        ///   FOR position_between(NUMBER, NUMBER, NUMBER)
        ///   USING position_im;.
        /// </summary>
        internal static string CreateIndextype {
            get {
                return ResourceManager.GetString("CreateIndextype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE AND RESOLVE NOFORCE JAVA CLASS USING BFILE (java_dir, &apos;Agent.class&apos;)
        ////.
        /// </summary>
        internal static string CreateJava {
            get {
                return ResourceManager.GetString("CreateJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE LIBRARY ext_lib IS &apos;/OR/newlib/ext_lib.so&apos;;
        ////.
        /// </summary>
        internal static string CreateLibrary {
            get {
                return ResourceManager.GetString("CreateLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE MATERIALIZED VIEW foreign_customers FOR UPDATE
        ///   AS SELECT * FROM sh.customers@remote cu
        ///   WHERE EXISTS
        ///     (SELECT * FROM sh.countries@remote co
        ///      WHERE co.country_id = cu.country_id);.
        /// </summary>
        internal static string CreateMaterializedView {
            get {
                return ResourceManager.GetString("CreateMaterializedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE MATERIALIZED VIEW LOG ON product_information 
        ///   WITH ROWID, SEQUENCE (list_price, min_price, category_id), PRIMARY KEY
        ///   INCLUDING NEW VALUES;.
        /// </summary>
        internal static string CreateMaterializedViewLog {
            get {
                return ResourceManager.GetString("CreateMaterializedViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE NO FORCE VIEW emp_view AS 
        ///   SELECT last_name, salary*12 annual_salary
        ///   FROM employees 
        ///   WHERE department_id = 20;.
        /// </summary>
        internal static string CreateNoForceView {
            get {
                return ResourceManager.GetString("CreateNoForceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE OPERATOR eq_op
        ///   BINDING (VARCHAR2, VARCHAR2) 
        ///   RETURN NUMBER 
        ///   USING eq_f;.
        /// </summary>
        internal static string CreateOperator {
            get {
                return ResourceManager.GetString("CreateOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE OUTLINE salaries FOR CATEGORY special
        ///   ON SELECT last_name, salary FROM employees;.
        /// </summary>
        internal static string CreateOutline {
            get {
                return ResourceManager.GetString("CreateOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PACKAGE emp_mgmt AS 
        ///   FUNCTION hire (last_name VARCHAR2, job_id VARCHAR2, 
        ///      manager_id NUMBER, salary NUMBER, 
        ///      commission_pct NUMBER, department_id NUMBER) 
        ///      RETURN NUMBER; 
        ///   FUNCTION create_dept(department_id NUMBER, location_id NUMBER) 
        ///      RETURN NUMBER; 
        ///   PROCEDURE remove_emp(employee_id NUMBER); 
        ///   PROCEDURE remove_dept(department_id NUMBER); 
        ///   PROCEDURE increase_sal(employee_id NUMBER, salary_incr NUMBER); 
        ///   PROCEDURE increase_comm(employee_id N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreatePackage {
            get {
                return ResourceManager.GetString("CreatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PACKAGE BODY emp_mgmt AS 
        ///   tot_emps NUMBER; 
        ///   tot_depts NUMBER; 
        ///FUNCTION hire 
        ///   (last_name VARCHAR2, job_id VARCHAR2, 
        ///    manager_id NUMBER, salary NUMBER, 
        ///    commission_pct NUMBER, department_id NUMBER) 
        ///   RETURN NUMBER IS new_empno NUMBER; 
        ///BEGIN 
        ///   SELECT employees_seq.NEXTVAL 
        ///      INTO new_empno 
        ///      FROM DUAL; 
        ///   INSERT INTO employees 
        ///      VALUES (new_empno, &apos;First&apos;, &apos;Last&apos;,&apos;first.example@oracle.com&apos;, 
        ///              &apos;(415)555-0100&apos;,&apos;18-JUN-02&apos;,&apos;IT_PROG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreatePackageBody {
            get {
                return ResourceManager.GetString("CreatePackageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PFILE = &apos;my_init.ora&apos; FROM SPFILE = &apos;s_params.ora&apos;;.
        /// </summary>
        internal static string CreatePfile {
            get {
                return ResourceManager.GetString("CreatePfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PRIVATE OUTLINE salaries FOR CATEGORY special
        ///   ON SELECT last_name, salary FROM employees;.
        /// </summary>
        internal static string CreatePrivateOutline {
            get {
                return ResourceManager.GetString("CreatePrivateOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PROCEDURE remove_emp (employee_id NUMBER) AS
        ///   tot_emps NUMBER;
        ///   BEGIN
        ///      DELETE FROM employees
        ///      WHERE employees.employee_id = remove_emp.employee_id;
        ///   tot_emps := tot_emps - 1;
        ///   END;
        ////.
        /// </summary>
        internal static string CreateProcedure {
            get {
                return ResourceManager.GetString("CreateProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROFILE new_profile
        ///  LIMIT PASSWORD_REUSE_MAX 10
        ///        PASSWORD_REUSE_TIME 30;.
        /// </summary>
        internal static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PUBLIC DATABASE LINK remote 
        ///   USING &apos;remote&apos;;.
        /// </summary>
        internal static string CreatePublicDatabaseLink {
            get {
                return ResourceManager.GetString("CreatePublicDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PUBLIC OUTLINE salaries FOR CATEGORY special
        ///   ON SELECT last_name, salary FROM employees;.
        /// </summary>
        internal static string CreatePublicOutline {
            get {
                return ResourceManager.GetString("CreatePublicOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PUBLIC ROLLBACK SEGMENT rbs_one
        ///   TABLESPACE rbs_ts;.
        /// </summary>
        internal static string CreatePublicRollbackSegment {
            get {
                return ResourceManager.GetString("CreatePublicRollbackSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PUBLIC SYNONYM offices 
        ///   FOR hr.locations;.
        /// </summary>
        internal static string CreatePublicSynonym {
            get {
                return ResourceManager.GetString("CreatePublicSynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE RESTORE POINT good_data;.
        /// </summary>
        internal static string CreateRestorePoint {
            get {
                return ResourceManager.GetString("CreateRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE ROLE dw_manager;.
        /// </summary>
        internal static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE ROLLBACK SEGMENT rbs_one
        ///   TABLESPACE rbs_ts;.
        /// </summary>
        internal static string CreateRollbackSegment {
            get {
                return ResourceManager.GetString("CreateRollbackSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SCHEMA AUTHORIZATION oe
        ///   CREATE TABLE new_product 
        ///      (color VARCHAR2(10)  PRIMARY KEY, quantity NUMBER) 
        ///   CREATE VIEW new_product_view 
        ///      AS SELECT color, quantity FROM new_product WHERE color = &apos;RED&apos; 
        ///   GRANT select ON new_product_view TO hr;.
        /// </summary>
        internal static string CreateSchema {
            get {
                return ResourceManager.GetString("CreateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SEQUENCE customers_seq
        /// START WITH     1000
        /// INCREMENT BY   1
        /// NOCACHE
        /// NOCYCLE;.
        /// </summary>
        internal static string CreateSequence {
            get {
                return ResourceManager.GetString("CreateSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SHARED DATABASE LINK remote 
        ///   USING &apos;remote&apos;;.
        /// </summary>
        internal static string CreateSharedDatabaseLink {
            get {
                return ResourceManager.GetString("CreateSharedDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SHARED PUBLIC DATABASE LINK remote 
        ///   USING &apos;remote&apos;;.
        /// </summary>
        internal static string CreateSharedPublicDatabaseLink {
            get {
                return ResourceManager.GetString("CreateSharedPublicDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SMALLFILE TABLESPACE tbs_01
        ///  DATAFILE &apos;tbs_f1.dbf&apos;
        ///  SIZE 20M AUTOEXTEND ON;.
        /// </summary>
        internal static string CreateSmallfileTablespace {
            get {
                return ResourceManager.GetString("CreateSmallfileTablespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SPFILE 
        ///   FROM PFILE = &apos;$ORACLE_HOME/work/t_init1.ora&apos;;.
        /// </summary>
        internal static string CreateSpfile {
            get {
                return ResourceManager.GetString("CreateSpfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE SYNONYM offices 
        ///   FOR hr.locations;.
        /// </summary>
        internal static string CreateSynonym {
            get {
                return ResourceManager.GetString("CreateSynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE employees_demo
        ///    ( employee_id    NUMBER(6)
        ///    , first_name     VARCHAR2(20)
        ///    , last_name      VARCHAR2(25) 
        ///         CONSTRAINT emp_last_name_nn_demo NOT NULL
        ///    , email          VARCHAR2(25) 
        ///         CONSTRAINT emp_email_nn_demo     NOT NULL
        ///    , phone_number   VARCHAR2(20)
        ///    , hire_date      DATE  DEFAULT SYSDATE 
        ///         CONSTRAINT emp_hire_date_nn_demo  NOT NULL
        ///    , job_id         VARCHAR2(10)
        ///       CONSTRAINT     emp_job_nn_demo  NOT NULL
        ///    , salary         NU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLESPACE normal_01
        ///  DATAFILE &apos;normal.dbf&apos;
        ///  SIZE 20M AUTOEXTEND ON;.
        /// </summary>
        internal static string CreateTablespace {
            get {
                return ResourceManager.GetString("CreateTablespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TEMPORARY TABLESPACE temp_demo
        ///   TEMPFILE &apos;temp01.dbf&apos; SIZE 5M AUTOEXTEND ON;.
        /// </summary>
        internal static string CreateTemporaryTablespace {
            get {
                return ResourceManager.GetString("CreateTemporaryTablespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE TRIGGER t
        ///  BEFORE
        ///    INSERT OR
        ///    UPDATE OF salary OR
        ///    UPDATE OF department_id OR
        ///    DELETE
        ///  ON employees
        ///BEGIN
        ///  CASE
        ///    WHEN INSERTING THEN
        ///      DBMS_OUTPUT.PUT_LINE(&apos;Inserting&apos;);
        ///    WHEN UPDATING(&apos;salary&apos;) THEN
        ///      DBMS_OUTPUT.PUT_LINE(&apos;Updating salary&apos;);
        ///    WHEN UPDATING(&apos;department_id&apos;) THEN
        ///      DBMS_OUTPUT.PUT_LINE(&apos;Updating department ID&apos;);
        ///    WHEN DELETING THEN
        ///      DBMS_OUTPUT.PUT_LINE(&apos;Deleting&apos;);
        ///  END CASE;
        ///END;
        ////.
        /// </summary>
        internal static string CreateTrigger {
            get {
                return ResourceManager.GetString("CreateTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create type test as object (a NUMBER(1));.
        /// </summary>
        internal static string CreateType {
            get {
                return ResourceManager.GetString("CreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create or replace type body test is
        ///
        ///constructor function test
        ///return self as result
        ///is
        ///begin
        ///  a := &apos;Hello world&apos;;
        ///  return;
        ///end;
        ///
        ///end;
        ////.
        /// </summary>
        internal static string CreateTypeBody {
            get {
                return ResourceManager.GetString("CreateTypeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE UNDO TABLESPACE undots1
        ///   DATAFILE &apos;undotbs_1a.dbf&apos;
        ///   SIZE 10M AUTOEXTEND ON
        ///   RETENTION GUARANTEE;.
        /// </summary>
        internal static string CreateUndoTablespace {
            get {
                return ResourceManager.GetString("CreateUndoTablespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE UNIQUE INDEX promo_ix ON orders
        ///   (CASE WHEN promotion_id =2 THEN customer_id ELSE NULL END,
        ///    CASE WHEN promotion_id = 2 THEN promotion_id ELSE NULL END);.
        /// </summary>
        internal static string CreateUniqueIndex {
            get {
                return ResourceManager.GetString("CreateUniqueIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW emp_view AS 
        ///   SELECT last_name, salary*12 annual_salary
        ///   FROM employees 
        ///   WHERE department_id = 20;.
        /// </summary>
        internal static string CreateView {
            get {
                return ResourceManager.GetString("CreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from oe.order where order_id = 1;.
        /// </summary>
        internal static string DeleteSimple {
            get {
                return ResourceManager.GetString("DeleteSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM (SELECT * FROM employees)
        ///WHERE job_id = &apos;SA_REP&apos;
        ///AND commission_pct &lt; .2;.
        /// </summary>
        internal static string DeleteSubquery {
            get {
                return ResourceManager.GetString("DeleteSubquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE TABLE (
        ///SELECT person_phones
        ///FROM person
        ///WHERE person_id = 1) p
        ///WHERE p.p_number = &apos;206-987-6543&apos;;.
        /// </summary>
        internal static string DeleteTableCollection {
            get {
                return ResourceManager.GetString("DeleteTableCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISASSOCIATE STATISTICS FROM PACKAGES  special_functions, other_functions, last_functions;.
        /// </summary>
        internal static string DisassociateStatistics {
            get {
                return ResourceManager.GetString("DisassociateStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP CLUSTER personnel
        ///   INCLUDING TABLES
        ///   CASCADE CONSTRAINTS;.
        /// </summary>
        internal static string DropCluster {
            get {
                return ResourceManager.GetString("DropCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP CONTEXT hr_context;.
        /// </summary>
        internal static string DropContext {
            get {
                return ResourceManager.GetString("DropContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop database;.
        /// </summary>
        internal static string DropDatabase {
            get {
                return ResourceManager.GetString("DropDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP DATABASE LINK remote;.
        /// </summary>
        internal static string DropDatabaseLink {
            get {
                return ResourceManager.GetString("DropDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP DIMENSION customers_dim;.
        /// </summary>
        internal static string DropDimension {
            get {
                return ResourceManager.GetString("DropDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP DIRECTORY bfile_dir;.
        /// </summary>
        internal static string DropDirectory {
            get {
                return ResourceManager.GetString("DropDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP DISKGROUP dgroup_01 INCLUDING CONTENTS;.
        /// </summary>
        internal static string DropDiskgroup {
            get {
                return ResourceManager.GetString("DropDiskgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop edition test cascade;.
        /// </summary>
        internal static string DropEdition {
            get {
                return ResourceManager.GetString("DropEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop flashback archive test;.
        /// </summary>
        internal static string DropFlashbackArchive {
            get {
                return ResourceManager.GetString("DropFlashbackArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FUNCTION oe.SecondMax;.
        /// </summary>
        internal static string DropFunction {
            get {
                return ResourceManager.GetString("DropFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP INDEX ord_customer_ix_demo;.
        /// </summary>
        internal static string DropIndex {
            get {
                return ResourceManager.GetString("DropIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP INDEXTYPE position_indextype FORCE;.
        /// </summary>
        internal static string DropIndextype {
            get {
                return ResourceManager.GetString("DropIndextype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP JAVA CLASS &quot;Agent&quot;;.
        /// </summary>
        internal static string DropJavaClass {
            get {
                return ResourceManager.GetString("DropJavaClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP JAVA RESOURCE &quot;Agent&quot;;.
        /// </summary>
        internal static string DropJavaResource {
            get {
                return ResourceManager.GetString("DropJavaResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP JAVA SOURCE &quot;Agent&quot;;.
        /// </summary>
        internal static string DropJavaSource {
            get {
                return ResourceManager.GetString("DropJavaSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP LIBRARY ext_lib;.
        /// </summary>
        internal static string DropLibrary {
            get {
                return ResourceManager.GetString("DropLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP MATERIALIZED VIEW emp_data;.
        /// </summary>
        internal static string DropMaterializedView {
            get {
                return ResourceManager.GetString("DropMaterializedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP MATERIALIZED VIEW LOG ON OE.customers;.
        /// </summary>
        internal static string DropMaterializedViewLog {
            get {
                return ResourceManager.GetString("DropMaterializedViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP OPERATOR eq_op;.
        /// </summary>
        internal static string DropOperator {
            get {
                return ResourceManager.GetString("DropOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP OUTLINE salaries;.
        /// </summary>
        internal static string DropOutline {
            get {
                return ResourceManager.GetString("DropOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PACKAGE emp_mgmt;.
        /// </summary>
        internal static string DropPackage {
            get {
                return ResourceManager.GetString("DropPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PACKAGE BODY emp_mgmt;.
        /// </summary>
        internal static string DropPackageBody {
            get {
                return ResourceManager.GetString("DropPackageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE hr.remove_emp;.
        /// </summary>
        internal static string DropProcedure {
            get {
                return ResourceManager.GetString("DropProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROFILE app_user CASCADE;.
        /// </summary>
        internal static string DropProfile {
            get {
                return ResourceManager.GetString("DropProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PUBLIC DATABASE LINK remote;.
        /// </summary>
        internal static string DropPublicDatabaseLink {
            get {
                return ResourceManager.GetString("DropPublicDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PUBLIC SYNONYM customers;.
        /// </summary>
        internal static string DropPublicSynonym {
            get {
                return ResourceManager.GetString("DropPublicSynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP RESTORE POINT good_data;.
        /// </summary>
        internal static string DropRestorePoint {
            get {
                return ResourceManager.GetString("DropRestorePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP ROLE dw_manager;.
        /// </summary>
        internal static string DropRole {
            get {
                return ResourceManager.GetString("DropRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP ROLLBACK SEGMENT rbs_one;.
        /// </summary>
        internal static string DropRollbackSegment {
            get {
                return ResourceManager.GetString("DropRollbackSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP SEQUENCE oe.customers_seq;.
        /// </summary>
        internal static string DropSequence {
            get {
                return ResourceManager.GetString("DropSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP SYNONYM customers;.
        /// </summary>
        internal static string DropSynonym {
            get {
                return ResourceManager.GetString("DropSynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE list_customers PURGE;.
        /// </summary>
        internal static string DropTable {
            get {
                return ResourceManager.GetString("DropTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLESPACE tbs_01 
        ///    INCLUDING CONTENTS 
        ///        CASCADE CONSTRAINTS;.
        /// </summary>
        internal static string DropTablespace {
            get {
                return ResourceManager.GetString("DropTablespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TRIGGER hr.salary_check;.
        /// </summary>
        internal static string DropTrigger {
            get {
                return ResourceManager.GetString("DropTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TYPE person_t FORCE;.
        /// </summary>
        internal static string DropType {
            get {
                return ResourceManager.GetString("DropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TYPE BODY data_typ1;.
        /// </summary>
        internal static string DropTypeBody {
            get {
                return ResourceManager.GetString("DropTypeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP USER bezel CASCADE;.
        /// </summary>
        internal static string DropUser {
            get {
                return ResourceManager.GetString("DropUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW emp_view;.
        /// </summary>
        internal static string DropView {
            get {
                return ResourceManager.GetString("DropView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLAIN PLAN FOR
        ///   SELECT * FROM dual;.
        /// </summary>
        internal static string ExplainPlan {
            get {
                return ResourceManager.GetString("ExplainPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASHBACK STANDBY DATABASE TO TIMESTAMP SYSDATE-1;.
        /// </summary>
        internal static string FlashbackDatabase {
            get {
                return ResourceManager.GetString("FlashbackDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLASHBACK TABLE test
        ///  TO TIMESTAMP (SYSTIMESTAMP - INTERVAL &apos;1&apos; minute);.
        /// </summary>
        internal static string FlashbackTable {
            get {
                return ResourceManager.GetString("FlashbackTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRANT SELECT, update
        ///   ON emp_view TO PUBLIC, scott;.
        /// </summary>
        internal static string Grant1 {
            get {
                return ResourceManager.GetString("Grant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRANT
        ///     CREATE ANY MATERIALIZED VIEW
        ///   , ALTER ANY MATERIALIZED VIEW
        ///   , DROP ANY MATERIALIZED VIEW
        ///   , QUERY REWRITE
        ///   , GLOBAL QUERY REWRITE
        ///   TO dw_manager,dw_USER
        ///   WITH ADMIN OPTION;.
        /// </summary>
        internal static string Grant2 {
            get {
                return ResourceManager.GetString("Grant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT ALL
        ///WHEN order_total &lt; 1000000 THEN
        ///INTO small_orders
        ///WHEN order_total &gt; 1000000 AND order_total &lt; 2000000 THEN
        ///INTO medium_orders
        ///WHEN order_total &gt; 2000000 THEN
        ///INTO large_orders
        ///SELECT order_id, order_total, sales_rep_id, customer_id
        ///FROM orders;.
        /// </summary>
        internal static string InsertMultitable {
            get {
                return ResourceManager.GetString("InsertMultitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO departments
        ///VALUES (departments_seq.nextval, &apos;Entertainment&apos;, 162, 1400);.
        /// </summary>
        internal static string InsertSimple {
            get {
                return ResourceManager.GetString("InsertSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO(SELECT EMP_ID,ENAME FROM EMP WHERE EMP_ID=1)VALUES(2,&apos;ABC&apos;);.
        /// </summary>
        internal static string InsertSubquery {
            get {
                return ResourceManager.GetString("InsertSubquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TABLE(
        ///SELECT person_phones
        ///FROM person
        ///WHERE person_id = 1)
        ///VALUES
        ///(&apos;H&apos;,&apos;206-987-6543&apos;);.
        /// </summary>
        internal static string InsertTableCollection {
            get {
                return ResourceManager.GetString("InsertTableCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCK TABLE a@remote, b 
        ///   IN SHARE MODE;.
        /// </summary>
        internal static string LockTable {
            get {
                return ResourceManager.GetString("LockTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO bonuses D
        ///   USING (SELECT employee_id, salary, department_id FROM employees
        ///   WHERE department_id = 80) S
        ///   ON (D.employee_id = S.employee_id)
        ///   WHEN MATCHED THEN UPDATE SET D.bonus = D.bonus + S.salary*.01
        ///     DELETE WHERE (S.salary &gt; 8000)
        ///   WHEN NOT MATCHED THEN INSERT (D.employee_id, D.bonus)
        ///     VALUES (S.employee_id, S.salary*.01)
        ///     WHERE (S.salary &lt;= 8000);.
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOAUDIT ROLE;.
        /// </summary>
        internal static string Noaudit {
            get {
                return ResourceManager.GetString("Noaudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURGE TABLE test;.
        /// </summary>
        internal static string Purge {
            get {
                return ResourceManager.GetString("Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENAME old_name TO new_name;.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVOKE SELECT, INSERT 
        ///    ON hr.table1 FROM usera, userc;.
        /// </summary>
        internal static string Revoke1 {
            get {
                return ResourceManager.GetString("Revoke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVOKE ALL 
        ///   ON orders FROM hr;.
        /// </summary>
        internal static string Revoke2 {
            get {
                return ResourceManager.GetString("Revoke2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVOKE CREATE TABLESPACE, CREATE TABLE 
        ///   FROM dw_manager, dw_user;.
        /// </summary>
        internal static string Revoke3 {
            get {
                return ResourceManager.GetString("Revoke3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVOKE ALL on java source &quot;/2a6f1ff1_LOBCOMPRESSOR&quot; from dw_manager;.
        /// </summary>
        internal static string Revoke4 {
            get {
                return ResourceManager.GetString("Revoke4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLLBACK TO SAVEPOINT test_sal;.
        /// </summary>
        internal static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVEPOINT test_sal;.
        /// </summary>
        internal static string Savepoint {
            get {
                return ResourceManager.GetString("Savepoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from dual;.
        /// </summary>
        internal static string Select1 {
            get {
                return ResourceManager.GetString("Select1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with a as (select *from dual) select * from a;.
        /// </summary>
        internal static string Select2 {
            get {
                return ResourceManager.GetString("Select2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET CONSTRAINTS ALL IMMEDIATE;.
        /// </summary>
        internal static string SetConstraints {
            get {
                return ResourceManager.GetString("SetConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @\home\oracle\start.sql.
        /// </summary>
        internal static string SqlPlusAt {
            get {
                return ResourceManager.GetString("SqlPlusAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOC
        ///# This is a multiline
        ///# comment
        ///# from obsolete
        ///# sql*plus syntax.
        /// </summary>
        internal static string SqlPlusDoc {
            get {
                return ResourceManager.GetString("SqlPlusDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @@\home\oracle\start.sql.
        /// </summary>
        internal static string SqlPlusDoubleAt {
            get {
                return ResourceManager.GetString("SqlPlusDoubleAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start \home\oracle\start.sql.
        /// </summary>
        internal static string SqlPlusStart {
            get {
                return ResourceManager.GetString("SqlPlusStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNCATE CLUSTER test_cluster REUSE STORAGE;.
        /// </summary>
        internal static string TruncateCluster {
            get {
                return ResourceManager.GetString("TruncateCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNCATE TABLE test_table PRESERVE MATERIALIZED VIEW LOG;.
        /// </summary>
        internal static string TruncateTable {
            get {
                return ResourceManager.GetString("TruncateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE sh.employees@remote
        ///SET salary = salary*1.1
        ///WHERE last_name = &apos;Baer&apos;;.
        /// </summary>
        internal static string UpdateSimple {
            get {
                return ResourceManager.GetString("UpdateSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update (select empname from emp) set empname = &apos;Test&apos;;.
        /// </summary>
        internal static string UpdateSubquery {
            get {
                return ResourceManager.GetString("UpdateSubquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TABLE(SELECT h.people FROM hr_info h
        ///WHERE h.department_id = 280) p
        ///SET p.salary = p.salary + 100;.
        /// </summary>
        internal static string UpdateTableCollection {
            get {
                return ResourceManager.GetString("UpdateTableCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE FUNCTION zblj wrapped
        ///a000000
        ///1
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///8
        ///189 158
        ///n/Zn2ExJiibNunotqpUJC744Vmgwg3nIrgw2f3SVALuwhVJvbwhys17J7FX0oFjs3x0SxayA
        ///H282ryAgn1Tp6sfe/Rm7Qyq6t2ubFKXAESC7BzPPerw/Z8ThWl4OtDa2r+otVsZfe19Nv/3q
        ///OP9SmuErftbeWNK6dgnVx3syZApRiVD4DT220uOC30d0uN7XCd6AnjdhES0V19QT3DZeU02C
        ///qKeSLN3Ncyey8j3Dejdb3Samo6StqXLq8YPYyEXBLzvDgLU/a5qE6n36WjkndjzR/00EjJZG
        ///NvhakJ3Vlm34HywtX516cO1TuOiF5vvYS4r/va1DBwquV5g4Mw==
        ///
        ////.
        /// </summary>
        internal static string WrappedFunction {
            get {
                return ResourceManager.GetString("WrappedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE LIBRARY zblj wrapped 
        ///a000000
        ///1
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///16
        ///24 59
        ///H/p7Czkf47nbLdCyJQeHa0u/qQ4wg04I9Z7AdBjDuAiBTjJt/gj1Cee9nrLLUjLMuHQr58tS
        ///dAj1yaammCS9lQ==
        ///
        ////.
        /// </summary>
        internal static string WrappedLibrary {
            get {
                return ResourceManager.GetString("WrappedLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PACKAGE zblj wrapped
        ///a000000
        ///1
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///9
        ///494 1de
        ///dS33nu1mpUpGxZcI0TjVzYgYyUQwgz1eDPbhfy+5MQ9/gAIcooMMnBzC+k2vNIVqg+tns7pj
        ///AoeSThOieeo75jVGQGwvmwDJvJBX1Bd+rEvPk6pQwC4exEP8jStPu90JbvL7ekLQGwmefTcC
        ///HKbSm9S9H0rm0iVZWgNEPiE6nlMqqGW2rxRVydRq72iyB2rouOYnhgOEUCsOZmohCQDZpseL
        ///Ook6zKr1JBF7UEr686B9y+W47dPs5bg9XGXb4UrYXOefz30x9VQxC/ZS23tLcthH2U9Op4xa
        ///HKilPidgbj4BXoogSsrHb5h7IAyRSadOfX4IRzCw4aG2Uqz5dkTAN1EBqmtHs1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrappedPackage {
            get {
                return ResourceManager.GetString("WrappedPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE PACKAGE BODY zblj wrapped
        ///a000000
        ///1
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///b
        ///12de 6c3
        ///c1af8IRn0WbL05nvA5u2Unfr27Iwg+1UBUiG3y/NA52sfW3Y4njjkCJWBuimbPCknzKZoWz/
        ///t8h5cfVtFLrbvWFE0gikh/WcIFWgonT6XbjJMIt28dzyc9D1vdsMrLrAtSlSt5oki2SWTyzn
        ///tozzqIEPA/Pxm9sHyoZn4RslyBmL91RKCLcMVKEV4MAuvqqhOkcNQee9k3RC53+oHG0+ndeT
        ///Vji9bm4PyCiwx3m3G6x1PMRYq7fnfJdveLTtiZxcHOLs7q/xlSOL12yZNQfOKVGfthuhe2V/
        ///HZbTQvH6IbdJzvpc1Av3Quabl8GirXVwFeLaxOuJgHTiHLvljWd2EbHH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrappedPackageBody {
            get {
                return ResourceManager.GetString("WrappedPackageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create type schema_name.type_name 
        /// TIMESTAMP &apos;2010-01-01:12:13:14&apos;
        /// OID &apos;8A3DAA85AABDAAE2E034080020EDC61B&apos; wrapped 
        ///a000000
        ///1
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///abcd
        ///d
        ///9c a2
        ///xByvrbM+14dgykYpNRIWwI7LR5owg5n0dLhcFnJc+vqu/0pyRwzZ0JYmVlpDCbh0K6W/m8Ay
        ///y7OPCanWL4BJLLEwtbgkscoCfMbKFyjGyu+yth0upHQqP0q84p5XPTCSvjpqtLgqQDk57HFn
        ///ppSxoMmmps7fZnE=
        ///
        ////.
        /// </summary>
        internal static string WrappedType {
            get {
                return ResourceManager.GetString("WrappedType", resourceCulture);
            }
        }
    }
}
