CREATE TABLE TOWNS
       (ID_TOWN NUMBER(10) NOT NULL,
        ID_COUNTRY VARCHAR2(3) NOT NULL,
        NAME VARCHAR2(100) NOT NULL
       );

ALTER TABLE TOWNS
 ADD (CONSTRAINT TOWNS_PK PRIMARY KEY 
  (ID_TOWN))
/


PROMPT Creating Foreign Key on 'TOWNS'
ALTER TABLE TOWNS ADD (CONSTRAINT
 TOWNS_COUNTRIES_FK FOREIGN KEY 
  (ID_COUNTRY) REFERENCES COUNTRIES
  (A3))
/

PROMPT Creating Index 'TOWNS_COUNTRIES_FK_I'
CREATE INDEX TOWNS_COUNTRIES_FK_I ON TOWNS
 (ID_COUNTRY)
/

